apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortner-deployment
  labels:
    app: shortner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortner
  template:
    metadata:
      labels:
        app: shortner
    spec:
      containers:
      - name: shortner
        image: alquama00s/linkshrink/shortner
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: redirector-postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: shortner-service
spec:
  type: NodePort
  selector:
    app: shortner
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30400

