spring:
  application:
    name: authn
  datasource:
    url: jdbc:postgresql://localhost:5433/linkshrink
    username: backend
    password: pass_876
  jpa:
    properties:
      hibernate:
        default_schema: linkshrink_sch

        
  devtools:
    add-properties: false

#server:
#  port: 8082


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true

cors:
  origins: http://10.211.10.30*