apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-storage
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

