spring:
  application:
    name: redirector
  redis:
#    host: localhost
#    port: 6379
    timeoutSec: 30
#    password: ""

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
#logging:
#  level:
#    root: DEBUG



fallbacks:
  viewUrl: https://www.bing.com


urls:
  shortner: http://192.168.49.2:30400
  authn: http://192.168.49.2:30200