spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linkshrink
    username: backend
    password: pass_876
  jpa:
    properties:
      hibernate:
        default_schema: linkshrink_sch
  application:
    name: shortner


fallbacks:
  viewUrl: https://www.bing.com
  expiryDuration: P1DT2H


