spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linkshrink
    username: backend
    password: pass_876
  jpa:
    properties:
      hibernate:
        default_schema: linkshrink_sch
  application:
    name: shortner
  devtools:
    add-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true



fallbacks:
  viewUrl: https://www.bing.com
  expiryDuration: P1DT2H


frontend:
  uri: http://10.211.10.30:8011
auth:
  server: http://192.168.49.2:30200