pipeline{
  agent {
        label 'server'
  }
  tools{
      gradle "gradle-7"
  }
  environment{
      JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'
  }
    stages{
        stage ('Checkout'){
            steps{
                cleanWs()
                sh "echo $JAVA_HOME"
                sh "git clone https://github.com/alquama00s/link_shrink.git ."
                sh "ls -la"
            }
        }
        stage('Build'){
            steps{
                nodejs(nodeJSInstallationName: 'NodeJS24') {
                    sh 'bash build-scripts/build.sh'
                }
                sh "docker rmi -f \$(docker images -q) || echo 'some problems deleting image...'"
                sh "bash build-scripts/buildImages.sh 3.0.$BUILD_NUMBER"
            }
        }
        stage('Process Images'){
                    steps{
                        sh "docker image ls"
                        sh "bash build-scripts/loadImages.sh"
                    }
                }
        stage('Deploy'){
            steps{
                echo 'Deploying....'
                sh "find k8s -type f -name '*.yml' -exec sed -i.bak 's/TAG/3.0.$BUILD_NUMBER/g' {} \\;"
                sh "cd k8s && bash app.sh"
            }
        }
        post {
                always {
                    archiveArtifacts artifacts: 'k8s/*.yml', allowEmptyArchive: true
                }
            }
    }
}